name: "AWS ECR Login Action"
description: "Log in to Amazon ECR using OIDC and AWS credentials"
inputs:
  repository-uri:
    description: "The ECR repository URI"
    required: true
  role-name:
    description: "The AWS role to assume"
    required: true
  aws-region:
    description: "The AWS region to use"
    required: false
    default: "ap-northeast-2"

outputs:
  repository-uri:
    description: "The repository URI used for ECR login"

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-name }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR
      id: ecr-login
      shell: bash
      run: |
        aws ecr get-login-password --region ${{ inputs.aws-region }} | \
        docker login --username AWS --password-stdin ${{ inputs.repository-uri }}

  outputs:
    repository-uri: ${{ inputs.repository-uri }}