# This is a basic workflow to help you get started with Actions

name: Deploy to Stage

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  notify-commits:
    runs-on: arc-runner-set
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 전체 히스토리 가져오기

      - name: Get List of Commits
        id: get_commits
        run: |
          git fetch origin stage  # stage 브랜치 정보 가져오기
          commits=$(git log --oneline origin/dev..origin/stage)
          echo "$commits"
          echo "::set-output name=commits::$commits"

      - name: Send slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: 'C07R2FM9X5F'
          payload: |
            {
              "text": "Merge from `dev` to `stage`",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "The following commits are being merged from dev to stage:\n${{ steps.get_commits.outputs.commits }}"
                  }
                }
              ]
            }

        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
