name: Runner Demo
on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: arc-runner-set
    steps:
      - name: echo demo
        run: echo "🎉 This job uses runner scale set runners!"

      - name: echo template
        uses: ./show-name-template.yml
        with:
          naming: 'GA Demo'
    
