name: Runner Demo
on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: arc-runner-set
    steps:
      - name: echo demo
        run: echo "🎉 This job uses runner scale set runners!"

  show-name:
    uses: oyg-pf-dev-prep/github-action-template/.github/workflows/show-name-template.yaml@main
    with:
      naming: 'GA Demo'
    

  helm-eks:
    uses: oyg-pf-dev-prep/github-action-template/.github/workflows/EKS-helm-deploy.yaml@main
    with:
      env: dev
      cluster-name: hansu-sandbox-eks
      aws-region: ap-northeast-2
      namespace: github-action-test
      release-name: nginx-action
    # secrets:
    #   AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
