name: Runner Demo
on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: arc-runner-set
    steps:
      - name: echo demo
        run: echo "🎉 This job uses runner scale set runners!"

  show-name:
    runs-on: arc-runner-set
    uses: oyg-pf-dev-prep/github-action-template/.github/workflows/show-name-template.yaml@main
    with:
      naming: 'GA Demo'
