name: Runner Demo
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  check-docker:
    runs-on: arc-runner-set
    steps:
      - name: Check docker --version
        run: docker --version

      - name: Check docker service status
        run: service docker status
      
      - name: Check docker root dir
        run: docker info | grep 'Docker Root Dir'

      - name: Check docker.sock
        run: ls -l /var/run/docker.sock

  deploy:
    name: Deploy
    runs-on: arc-runner-set
    environment: dev
  
    steps:
      - name: Configure AWS Credential
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Deploy
        uses: bitovi/github-actions-deploy-eks-helm@v1.2.10
        with:
          aws-region: ap-northeast-2
          cluster-name: hansu-sandbox-eks
          chart-repository: oci://registry-1.docker.io/
          chart-path: bitnamicharts/nginx
          namespace: github-action-test
          name: nginx-action

  helm-eks:
    uses: oyg-pf-dev-prep/github-action-template/.github/workflows/EKS-helm-deploy.yaml@main
    with:
      env: dev
      cluster-name: hansu-sandbox-eks
      aws-region: ap-northeast-2
      namespace: github-action-test
      release-name: nginx-action
    # secrets:
    #   AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
