name: Runner Demo
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  helm-eks:
    uses: oyg-pf-dev-prep/github-action-template/.github/workflows/EKS-helm-deploy.yaml@main
    with:
      env: dev
      cluster-name: hansu-sandbox-eks
      aws-region: ap-northeast-2
      namespace: github-action-test
      release-name: nginx-action
    # secrets:
    #   AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
